modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Side Slabs - place slabs on their sides!
'''

[[dependencies.sideslabs]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sideslabs]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
